name: go-build-and-unit-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    strategy:
        matrix:
            go-version: [1.21.x]
            os: [ ubuntu-latest ]
            goos: [ linux ]
            goarch: [amd64, arm64, ppc64le]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build test for ${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
        run: GOARCH="${TARGET}" go build main.go

      - name: Go test
        run: go test -race ./...
